name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:

    name: Build and test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: '1.10.3' # Define the elixir version [required]
        otp-version: '22.3' # Define the OTP version [required]
    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: deps-${{ hashFiles('**/mix.lock') }}
        restore-keys: deps
    - name: Restore plt file
      uses: actions/cache@v2
      with:
        path: _build
        key: build-${{ hashFiles('**/mix.lock') }}
        restore-keys: build
    - name: Install dependencies
      run: mix deps.get
    - name: Check code quality
      run: mix code_quality
    - name: Compile
      run: MIX_ENV=test mix compile --warnings-as-errors
    - name: Run tests
      run: mix test
